# promise中的reject

Promise 对象用于一个异步操作的最终完成（或失败）及其结果值的表示。简单点说，它就是用于处理异步操作的，异步处理成功了就执行成功的操作，异步处理失败了就捕获错误或者停止后续操作。

```javascript
new Promise(
	/* executor */
	function(resolve, reject) {
		if (/* success */) {
			// ...执行代码
			resolve()
		} else { /* fail */
			// ...执行代码
			reject()
        }
    }
)
```

其中，Promise中的参数`executor`是一个执行器函数，它有两个参数`resolve`和`reject`。它内部通常有一些异步操作，如果异步操作成功，则可以调用resolve()来将该实例的状态置为`fulfilled`，即已完成的；如果一旦失败，可以调用reject()来将该实例的状态置为`rejected`，即失败的。

> 1. pending
>
>    初始状态，也称为未定状态，就是初始化Promise时，调用executor执行器函数后的状态。
>
> 2. fulfilled
>
>    完成状态，意味着异步操作成功。
>
> 3. rejected
>
>    失败状态，意味着异步操作失败。

```javascript
var promise = new Promise((resolve, reject) => {
    console.log(1)
    reject()
})
promise.then(
	data => {
    	console.log(2)
 	},
	err => {
    	console.log(3)
 	}
).catch(
    res => {
        console.log(4)
	}
)
// 1 3
```

> **reject后的东西，一定会进入then中的第二个回调，如果then中没有写第二个回调，则进入catch**

```javascript
var promise = new Promise((resolve, reject) => {
    console.log(1)
    reject()
})
promise.then(
    data => {
    	console.log(2)
 	}
).catch(
    res => {
        console.log(4)
	}
)
// 1 4
```

面试题：

```javascript
setTimeout(()=> { console.log(1) })
let promise = new Promise(function(resolve, reject){
	console.log(2)
	reject()
})
promise.then(
    res => {
          console.log(3)
    },
    res => {
          console.log(4)
    }
)
// 2 4 1
```

